config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #
  root 'haupt#main'
  get 'impressum', to: 'haupt#impressum'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/my_data.rb
class MyData
  def self.email
    "sprachunterrichtonline@gmail.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/haupt_controller.rb
class HauptController < ActionController::Base
  layout 'application'

  def main

  end

  def impressum
    @noindex = true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/haupt/impressum.html.erb
<h1><%= link_to '< Zurück zur Hauptseite', root_path %></h1>
<h2>Impressum</h2>
<p>
  Judith Hölzle<br>
  Wachsbleiche 5<br>
  53111 Bonn
</p>
<p>
  E-Mail: <%= MyData.email %>><br>
</p>

app/views/haupt/main.html.erb
<h1><b>Sprachunterricht und Sprachnachhilfe</b></h1>
<p>
  Ich biete persönliche Hilfe beim Erlernen von Sprachen für Erwachsene, Jugendliche & Kinder in Gruppen- oder Einzelterminen an.<br>
  Das Angebot ist primär online, aber in Absprache gebe ich meinen Unterricht auch persönlich vor Ort im Raum Köln/Bonn.
</p>
<b><%=  mail_to MyData.email,"Kontaktieren Sie mich unter " + MyData.email,  class: "button" %></b>
<br><br>
<hr>
<h2>Angebotene Sprachen</h2>
<ul>
  <li>Deutsch / Deutsch als Fremdsprache</li>
  <li>Französisch</li>
</ul>
<h2>Über mich</h2>
<p>
  Elf Jahre war ich als staatlich anerkannte Studienrätin für die Fächer Deutsch und Französisch der Sekundarstufe I und II an Gymnasien tätig. <br>
  Des Weiteren habe ich zwei Jahre im französischen Ausland studiert und gearbeitet. Außerdem besitze ich eine universitäre Zusatzqualifikation bzw. Ausbildung für "Deutsch - als Fremdsprache".<br><br>
  Meine <u>langjährige Erfahrung & Qualifikation</u> helfen mir, mich auf die indidividuellen Bedürfnisse meiner Schülerinnen und Schüler einzustellen und gemeinsam mit diesen am individuellen Lernerfolg zu arbeiten.
</p>
<h2>Motivation</h2>
<p>
  <%# Ich halte persönliche Hilfe für erfolgsversprechender, um Sprachen zu erlernen, da unter anderem auf die Stärken und Schwächen der Schüler mehr Rückicht genommen werden kann.<br><br>  %>
  Häufig ist es im Schulalltag und in der Klasse nicht möglich, ausreichend auf die individuellen Lernbedürfnisse der Schüler einzugehen.<br>
  Hierbei fehlt es den Lehrern oft an Zeit, besonders schwierige Lerninhalte ausgiebig zu üben und als Schülerin oder Schüler individuelle Rückmeldungen zu erhalten und umzusetzen.<br>
  <br>
  Meine langjährige Tätigkeit am Gymnasium erlaubt es mir, mit den Abläufen und Anforderungen genauestens vertraut zu sein.<br><br>
  Durch individuellen Sprachunterricht können Lernerfolge und eigene Ziele besser erreicht werden.<br>
  Somit kann ich gezielt meine Kompetenzen einsetzen, um Selbstvertrauen beim Lernprozess zu schaffen und die entsprechenden Sprach- und Analysefähigkigkeiten bei den Schülerinnen und Schülern zu verbessern.
</p>
<h2>Preis</h2>
<p>Der Stundenpreis wird individuell besprochen und ist abhängig von Gruppengröße, Anreise-, Vorbereitungs- bzw. Nachbereitungsaufwand. Ich rechne normalweise stundenbasiert ab.</p>
<h2><b>Über Ihre Kontaktaufnahme würde ich mich sehr freuen.</b></h2>
<b><%=  mail_to MyData.email,"Schreiben Sie mir unter " + MyData.email, class: "button" %></b>

<br><br>
<hr>
<br>
<%= link_to 'Impressum', impressum_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de">
  <head>
    <% if Rails.env.production? %>
      <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-TPXRJJ63F3"></script>
      <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-TPXRJJ63F3');</script>
    <% end %>
    <title>
      <% if Rails.env.staging? %>
        STAGING |
      <% elsif Rails.env.development? %>
        DEV |
      <% end %>
      Sprachunterricht und Sprachnachhilfe Judith Hölzle
    </title>
    <%= favicon_link_tag asset_path("favicon.ico") %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <% if @noindex %>
      <meta name="robots" content="noindex">
    <% end %>
    <link rel=”canonical” href=https://sprachunterricht-online.de/>
    <meta name="description" content="Online Sprachnachhilfe in Deutsch (auch als Fremdsprache) und Französisch von studierter Lehrerin">
  </head>
  <body>
    <%= yield %>
  </body>
</html>